$('.brand').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
		320:{
            items:1
        },
        700:{
            items:1
        },
        1000:{
            items:2
        }
    }
})